version: '3.5'
services:
  datenort:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: rocketbaseio/datenort:latest
    ports:
      - "8081:8081"

