global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["docker.for.mac.host.internal:8083"]

  - job_name: "node"
    static_configs:
      - targets: ["docker.for.mac.host.internal:9100"]